platform :ios, “9.0”

target ‘ReactNativeDemo’ do
  # 取决于你的工程如何组织，你的node_modules文件夹可能会在别的地方。
  # 请将:path后面的内容修改为正确的路径（一定要确保正确～～）。
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path, :subspecs => [
   'Core',
    'ART',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
  ]
end
